config/routes.rb
Rails.application.routes.draw do

  resources :words, except: :show
  resources :tests, only: [:new, :update]
  #not restful, but I like this url style.
  resources :dictionaries, except: :show do
    member do
      post 'choose'
    end
  end

  devise_for :users

  root to: "words#index"

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  validates :name, presence: true
  validates :name, uniqueness: {scope: :user_id}
  has_many :words, dependent: :destroy
  has_many :tests, dependent: :destroy

  def test_type_ids
    Test::TEST_TYPE_IDS - exclude_test_types
  end

  def test_type_ids=(test_type_ids)
    self.exclude_test_types = Test::TEST_TYPE_IDS - test_type_ids.map(&:to_i)
  end

  def test_types
    Test::TEST_TYPES.values_at(*test_type_ids)
  end

  def test_method_ids
    Test::TEST_METHOD_IDS - exclude_test_method_ids
  end

  def test_method_ids=(test_method_ids)
    self.exclude_test_method_ids = Test::TEST_METHOD_IDS - test_method_ids.map(&:to_i)
  end

  def test_missing_letters?
    test_method_ids.include? Test::TEST_METHODS.index(:missing_letters)
  end

  def test_select_option?
    test_method_ids.include? Test::TEST_METHODS.index(:select_option)
  end

  def test_word_sql
    words.select('*, ( correct + 1) / (incorrect + 1 ) as ratio').order('ratio').limit(10).sample
  end

  def test_word(params={})
    Pickup.new(words.search(params), key_func: Proc.new(&:itself), weight_func: Proc.new(&:weight)).pick #{|v| v**2}
  end

  def import(words)
    Word.import(self.id, words)
  end

  def valid_option_count
    rand(select_option_from..select_option_to)
  end

  def label_for_column column
    case column.to_sym
    when :word
      word_column_label
    when :word_upcase
      I18n.t 'label.word_upcase', word: word_column_label
    when :translation
      translation_column_label
    else
      I18n.t "label.#{column}", default: ''
    end
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy, :choose]
  def index
    @dictionaries = current_user.dictionaries
    redirect_to new_dictionary_path if @dictionaries.length.zero?
  end

  def choose
    select_and_view
  end

  def new
    @dictionary = Dictionary.new(user: current_user)
  end

  def edit
  end

  def create
    @dictionary = Dictionary.new(dictionary_params)
    @dictionary.user = current_user
    if @dictionary.save
      select_and_view
    else
      render :new
    end
  end

  def update
    if @dictionary.update(dictionary_params)
      select_and_view
    else
      render :edit
    end
  end

  def destroy
    @dictionary.destroy
    redirect_to dictionaries_path, notice: 'Dictionary was successfully destroyed.'
  end

  private

    def set_dictionary
      @dictionary = current_user.dictionaries.find(params[:id])
    end

    def select_and_view
      current_user.update_column(:current_dictionary_id, @dictionary.id)
      redirect_to words_path
    end

    def dictionary_params
      params.require(:dictionary).permit(
        :name,
        :word_column_label,
        :translation_column_label,
        test_type_ids: [],
        test_method_ids: []
      )
    end
end

app/views/dictionaries/_form.html.erb
<% if @dictionary.errors.any? %>
  <div class="flash flash-alert">
    <%= @dictionary.errors.full_messages.to_sentence %>
  </div>
<% end %>
<div class="form card">
  <h2><%= @dictionary.persisted? ? 'Edit settings' : 'New Dictionary' %></h2>

  <%= form_for(@dictionary) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :word_column_label, 'New language' %>
    <%= f.text_field :word_column_label %>
  </div>

  <div class="field">
    <%= f.label :translation_column_label, 'Familiar language' %>
    <%= f.text_field :translation_column_label %>
  </div>

  <div class="field">
    <%= f.label :test_method_ids, 'Test methods' %>
    <% Test::TEST_METHODS.each_with_index do |method, i| %>
      <div class="checkbox-list">
        <%= f.check_box :"test_method_ids", {multiple: true, id: "test_method_ids_#{i}"}, i, nil %>
        <label for="test_method_ids_<%= i %>">
          <%=t "label.#{method}" %></label>
      </div>
    <% end -%>
  </div>

  <div class="field">
    <%= f.label :test_type_ids, 'Test types' %>
    <% Test::TEST_TYPES.each_with_index do |type, i| %>
      <div class="checkbox-list">
        <%= f.check_box :"test_type_ids", {multiple: true, id: "test_type_ids_#{i}"}, i, nil %>
        <label for="test_type_ids_<%= i %>">
          <%=t 'label.q_a', q: @dictionary.label_for_column(type.first), a: @dictionary.label_for_column(type.last) %></label>
      </div>
    <% end -%>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

  <%= link_to 'Delete dictionary', @dictionary, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button destroy' if @dictionary.persisted? %>
  <%= link_to 'Cancel', dictionaries_path %>
</div>

app/views/dictionaries/edit.html.erb
<%= render 'form' %>

app/views/dictionaries/index.html.erb
<div class="form card dictionaries">
  <h2>Languages</h2>
  <% @dictionaries.each do |dictionary| %>
    <div class="field"><%= link_to dictionary.name, choose_dictionary_path(dictionary), method: :post %></div>
  <% end %>
  <div class="actions">
    <%= link_to 'New Dictionary', new_dictionary_path, class: :button %>
  </div>
</div>

app/views/dictionaries/new.html.erb
<%= render 'form' %>