config/routes.rb
Rails.application.routes.draw do

  resources :words, except: :show
  resources :tests, only: [:new, :update]
  #not restful, but I like this url style.
  resources :dictionaries, except: :show do
    member do
      post 'choose'
    end
  end

  devise_for :users

  root to: "words#index"

end

app/models/word.rb
class Word < ActiveRecord::Base

    NUMBERS = [:singular, :plural]


  include Noun
  include Verb
  include Preposition
  include Adjective

  CLASSES = [
    :adjective,
    :article,
    :noun,
    :letter,
    :preposition,
    :pronoun,
    :verb
  ]

  belongs_to :dictionary
  validates :dictionary_id, presence: true
  validates :lexical_form, presence: true, length: {minimum:1}
  delegate :user, to: :dictionary
  has_many :tests, dependent: :destroy

  def display_word_class
    return word_class if word_class.present?
    return :preposition if preposition?
    return :adjective if adjective?
    return :noun if noun?
    return :verb if verb?
  end

  def word_class
    read_attribute(:word_class).to_sym if read_attribute(:word_class).present?
  end

  def lexical_form=(entry)
    word, translation = Word.split_lexical_form(entry)
    write_attribute(:translation, translation) if translation.present?
    write_attribute(:lexical_form, word)
    entry
  end

  def lexical_form
    read_attribute(:lexical_form).try(:strip) || ''
  end

  def term
    return preposition_term if preposition?
    return noun_term if nounish?
    return adjective_term if adjective?
    return lexical_form
  end

  def lexical_tail
    return preposition_lexical_tail if preposition?
    return noun_lexical_tail if nounish?
    return adjective_lexical_tail if adjective?
  end

  def self.split_lexical_form(lexical_form)
    if lexical_form.include?("|")
      lexical_form.strip.split(/\s*\|\s*/)
    else
      lexical_form.strip
    end
  end

  def self.import(dictionary_id, words)
    words.each_line do |line|
      next if line.starts_with?('#') #it's a comment
      entry, translation = split_lexical_form(line.strip)
      unless where(lexical_form:entry, dictionary_id: dictionary_id).exists?
        #only modify new things.
        create(lexical_form: line.strip, dictionary_id: dictionary_id)
      end
    end
  end

  def weight
    if incorrect.zero? && correct.zero?
      Word.select(:incorrect).max(:incorrect) + 1
    elsif correct.zero?
      incorrect.to_f
    elsif incorrect.zero?
      0.5 / correct.to_f
    else
      incorrect.to_f / correct.to_f
    end
  end

  def stem
    @stem ||=
    case display_word_class
    when :noun, :pronoun
      noun_stem
    when :verb
      verb_stem
    when :adjective
      adjective_stem
    else
      term
    end
  end

  #accents were futzing with sorting.
  def sort_term
    term.mb_chars.downcase.gsub(/[ἀἁᾀᾁ]/, 'α')
                          .gsub(/[ἐἑ]/,   'ε')
                          .gsub(/[ἠἡᾐᾑ]/, 'η')
                          .gsub(/[ἰἱ]/,   'ι')
                          .gsub(/[ὀὁ]/,   'ο')
                          .gsub(/[ὐὑ]/,   'υ')
                          .gsub(/[ὠὡᾠᾡ]/, 'ω')
  end

  ######

  def variants
    return Noun::NOUN_VARIANTS if nounish?
    return Verb::VERB_VARIANTS if verb?
    return Adjective::ADJECTIVE_VARIANTS if adjectivish?
    return []
  end

  def variant_columns
    return Noun::NOUN_VARIANT_COLUMNS if nounish?
    return Verb::VERB_VARIANT_COLUMNS if verb?
    return Adjective::ADJECTIVE_VARIANT_COLUMNS if adjectivish?
    return []
  end

  def variant_combinations
    return Noun::NOUN_VARIANT_COMBINATIONS if nounish?
    return Verb::VERB_VARIANT_COMBINATIONS if verb?
    return Adjective::ADJECTIVE_VARIANT_COMBINATIONS if adjectivish?
    return []
  end

  def variants_with_answer(answer_method)
    column_index = variant_columns.index(answer_method)
    return [] unless column_index
    answers = variant_combinations.map { |v| v[column_index] }
    variants.map{|v|:"display_#{v}"}.zip(answers)
  end

  def options(answer_method)
    case answer_method.to_sym
    when :word_class, :display_word_class
      CLASSES.map(&:to_s)
    when :takes_case, :display_takes_case
      Preposition::PREPOSITION_CASES.map(&:to_s)
    when :case, *Noun::CASES
      Noun::CASES.map(&:to_s)
    when *Verb::PERSONS
      Verb::PERSONS.map(&:to_s)
    when :display_gender, *Noun::GENDERS
      Noun::GENDERS.map(&:to_s)
    when :number, *Word::NUMBERS
      Word::NUMBERS.map(&:to_s)
    when :translation
      dictionary_test_options(answer_method)
    end
  end

  def dictionary_test_options(answer_method)
    options = Word
              .where(dictionary_id:dictionary_id)
              .where.not(id:id)
              .limit(dictionary.valid_option_count)
              .order('RANDOM()')
    options.to_a.map(&answer_method.to_sym)
    .tap { |a| a << self.send(answer_method.to_sym) }
    .shuffle
  end

  def expanded_test_types
    variant_types = []
    dictionary.test_types.reject do |test_type|
      if test_type.first == :term_variant
        if variant_columns.include?(test_type.last)
          variant_types += variants_with_answer(test_type.last)
        else
          variant_types += variants.map {|v| [v, test_type.last] }
        end
        true
      else
        false
      end
    end + variant_types
  end

  def test_types
    expanded_test_types.reject do |test_type|
      method_or_symbol(test_type.first).to_s.blank? ||
      method_or_symbol(test_type.last ).to_s.blank?
    end
  end

  def test_type
    test_types.sample
  end

  def ending(variant)
    return noun_ending(variant) if nounish?
    return verb_ending(variant) if verb?
  end

  def method_or_symbol(symbol)
    return send(symbol) if self.respond_to?(symbol)
    return symbol
  end

  def regular?
    return regular_noun? if nounish?
    return regular_verb? if verb?
    return regular_adjective? if adjectivish?
    return regular_preposition? if preposition?
    return false
  end

  def self.orthograph word
    word.gsub(/ς/,  'σ')
        .gsub(/κσ/, 'ξ')
        .gsub(/πσ/, 'ψ')
        .gsub(/σ$/, 'ς')
  end

  def self.search params
    params = params.symbolize_keys.to_h
    word_class = params.delete(:word_class)
    regular = params.delete(:regular)
    id = params.delete(:word_id)
    params[:id] = id if id
    output = where(params).to_a
    output = output.select{|w| w.display_word_class == word_class.to_sym } if word_class.present?
    output = output.select{|w| w.regular?.to_s == regular } if regular.present?
    output
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dictionary
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = @dictionary.words.search(search_params).sort_by(&:sort_term)
    @word = new_word
  end

  def new
    @word = new_word
  end

  def edit
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      if request.xhr?
        render :create
      else
        redirect_to words_path
      end
    else
      render :new
    end
  end

  # PATCH/PUT /words/1
  def update
    if @word.update(word_params)
      if request.xhr?
        render :update
      else
        redirect_to words_path
      end
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    if request.xhr?
      render :destroy
    else
      redirect_to words_path
    end
  end

  private

    def set_word
      @word = current_user.words.find(params[:id])
    end

    def set_dictionary
      @dictionary = current_user.current_dictionary
      redirect_to dictionaries_path unless @dictionary
    end

    def test_params
      params.require(:test).permit(:given_answer)
    end

    def new_word
      Word.new(dictionary: @dictionary)
    end

    # Only allow a trusted parameter "white list" through.
    def word_params
      params.require(:word).permit(
        :word_class,
        :lexical_form,
        :translation
      ).merge(dictionary_id: @dictionary.id)
    end

    def search_params
      params.permit(
        :word_class,
        :regular,
        :translation
      )
    end
end

app/views/words/_form.html.erb
<%= form_for(@word, remote: true, html: {class: 'table-body', id: dom_id(@word)}) do |f| %>
  <div class="table-row">
    <div class="cell word-class input">
      <%= f.select :word_class, options_for_select(word_classes, f.object.display_word_class), {prompt: '-word class-'}, class: 'word_class' %>
    </div>
    <div class="cell word input">
      <div class="input-wrapper">
        <%= f.text_field :lexical_form, class: 'word', autofocus: @word.persisted?, placeholder: @dictionary.word_column_label %>
      </div>
    </div>
    <div class="cell translation input">
      <div class="input-wrapper">
        <%= f.text_field :translation, class: 'translation', placeholder: @dictionary.translation_column_label %>
      </div>
    </div>
    <div class="cell action">
        <%= f.submit 'Save' %>
        <%= link_to 'Delete', @word, method: :delete, class: 'button destroy', data: { confirm: 'Are you sure?', remote: true } if @word.persisted? %>
    </div>
  </div>

  <%# adjective stuff %>
  <div class="table-row word-class-variant adjective article <%= 'hidden' unless @word.adjective? %>">
    <div class="cell"></div>
  <% Noun::GENDERS.each do |gender| %>
    <div class="cell field-label"><%= gender.to_s.humanize %></div>
  <% end %>
  </div>

  <% Noun::NOUN_VARIANTS.each do |variant| %>
    <div class="table-row word-class-variant adjective article <%= 'hidden' unless @word.adjective? %>">
      <div class="cell word-class field-label">
        <%= variant.to_s.humanize %>
      </div>
      <% Noun::GENDERS.each do |gender| %>
        <div class="cell word input" style="min-width:<%= f.object.send(:"display_#{gender}_#{variant}").to_s.length.to_f / 1.5 %>em">
          <div class="input-wrapper">
            <%= f.text_field :"#{gender}_#{variant}", class: 'variant', placeholder: f.object.send(:"display_#{gender}_#{variant}") %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%# verb stuff %>
  <div class="table-row word-class-variant verb <%= 'hidden' unless @word.verb? %>">
    <div class="cell"></div>
  <% Verb::TENSES.each do |tense| %>
    <div class="cell field-label"><%= tense.to_s.humanize %></div>
  <% end %>
  </div>

  <% Verb::VERB_VARIANTS.each do |variant| %>
    <div class="table-row word-class-variant verb <%= 'hidden' unless @word.verb? %>">
      <div class="cell word-class field-label">
        <%= variant.to_s.humanize %>
      </div>
      <% Verb::TENSES.each do |tense| %>
        <div class="cell word input" style="min-width:<%= f.object.send(:"display_#{tense}_#{variant}").to_s.length.to_f / 1.5 %>em">
          <div class="input-wrapper">
            <%= f.text_field :"#{tense}_#{variant}", class: 'variant', placeholder: f.object.send(:"display_#{tense}_#{variant}") %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%# noun stuff %>
  <div class="table-row word-class-variant noun pronoun <%= 'hidden' unless @word.nounish? %>">
    <div class="cell"></div>
    <div class="cell field-label">Singular</div>
    <div class="cell field-label">Plural</div>
  </div>
  <% Noun::CASES.each do |word_case| %>
    <div class="table-row word-class-variant noun pronoun <%= 'hidden' unless @word.nounish? %>">
      <div class="cell word-class field-label">
        <%= word_case.to_s.humanize %>
      </div>
      <div class="cell word input" style="min-width:<%= f.object.send(:"display_singular_#{word_case}").to_s.length.to_f / 1.5 %>em">
        <div class="input-wrapper">
          <%= f.text_field :"singular_#{word_case}", class: 'variant', placeholder: f.object.send(:"display_singular_#{word_case}") %>
        </div>
      </div>
      <div class="cell word input" style="min-width:<%= word_case == :vocative ? 0 : f.object.send(:"display_plural_#{word_case}").to_s.length.to_f / 1.5 %>em">
        <div class="input-wrapper"  >
          <%= f.text_field :"plural_#{word_case}", class: 'variant', placeholder: f.object.send(:"display_plural_#{word_case}") unless word_case == :vocative %>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

app/views/words/_word.html.erb
<%= link_to edit_word_path(word), remote: true, id: dom_id(word), class: 'table-row' do %>
    <div class="cell field-label"><%= word.display_word_class %></div>
    <div class="cell word"><%= word.term %><span class="tail"><%= word.lexical_tail %></span></div>
    <div class="cell translation"><%= word.translation %></div>
    <div class="cell action"><span class="button">Edit</span>
    <div class="cell proficiency"><%= word.weight %></div>
  </div>
<% end %>

app/views/words/create.js.erb
$('#new_word').replaceWith('<%=j render partial: 'word', locals: {word: @word} %>');

<% @word = Word.new(dictionary: @dictionary) %>
$('#words .table-body').prepend('<%= j render partial: 'form' %>');
$('#new_word input[type="text"]').first().focus();

app/views/words/destroy.js.erb
$('#<%= dom_id(@word) %>').remove();

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/edit.js.erb
$('#<%= dom_id(@word) %>').replaceWith('<%=j render partial: 'form' %>');

app/views/words/index.html.erb
<% if flash[:notice].present? %>
  <div class="flash flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="flash flash-alert">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="card">
  <h2><%= @dictionary.name %>
    <%= link_to 'i', edit_dictionary_path(@dictionary), class: 'button settings-button secondary' %>
  </h2>
  <%# not a real table for a: responsive and b: row=form reasons. %>
  <div class="table words" id="words">
    <div class="table-head">
      <div class="table-row">
        <div class="cell"></div>
        <div class="cell word"><%= @dictionary.word_column_label %></div>
        <div class="cell translation"><%= @dictionary.translation_column_label %></div>
        <div class="cell"></div>
      </div>
      <div class="table-row field-label-row">
        <div class="cell field-label">
          <div class="field-label-inner">New word</div>
        </div>
      </div>
    </div>
    <%= render partial: 'form' %>
    <%= render @words %>
  </div>
</div>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/new.js.erb
$('#new_word, #<%= dom_id(@word) %>').replaceWith('<%=j render partial: 'form' %>');
$('#<%= dom_id(@word) %> input[type="text"]').first().focus();
$('#<%= dom_id(@word) %> .field_with_errors input[type="text"]').first().focus();

app/views/words/update.js.erb
$('#<%= dom_id(@word) %>').replaceWith('<%=j render partial: 'word', locals: { word: @word}  %>');