config/routes.rb
Rails.application.routes.draw do

  resources :words, except: :show
  resources :tests, only: [:new, :update]
  #not restful, but I like this url style.
  resources :dictionaries, except: :show do
    member do
      post 'choose'
    end
  end

  devise_for :users

  root to: "words#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lexicon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 class="brand">
        lexicon;
      </h1>
      <% if user_signed_in? %>
        <nav>
          <%= link_to 'words', words_path, class: :button %>
          <%= link_to 'test', new_test_path, class: :button %>
          <%= link_to 'languages', dictionaries_path, class: :button %>
          <%= link_to('Sign out', destroy_user_session_path, :method => :delete, class: 'button sign-out destroy') %>
        </nav>
      <% end -%>
    </div>
    <div class="body">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
    </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/devise.html.erb
<% content_for :content do %>
<% if flash[:notice].present? %>
  <div class="flash flash-notice devise-flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="flash flash-alert devise-flash">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="form devise card">
  <%= yield %>
</div>
<% end %>
<%= render template: 'layouts/application' %>